version: '2'
services:
    php:
        build: ./docker/php/
#        image: disc/php-amqp
        environment:
            TIMEZONE: Asia/Novosibirsk
        volumes:
            - ./app:/var/www/app
            - ./docker/php/host.conf:/etc/apache2/sites-enabled/000-default.conf
        working_dir: /var/www/app
        ports:
            - "8080:80"
        links:
            - rabbitmq
    # Databases
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
              MYSQL_ROOT_PASSWORD: "rootpw"
              MYSQL_DATABASE: "microservice"
              MYSQL_USER: "admin"
              MYSQL_PASSWORD: "admin"
        volumes:
            - ./mysql:/var/lib/mysql
    # Tools
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: "mysql"
        depends_on:
            - mysql
        ports:
            - "8085:80"
    #Queue
    rabbitmq:
        image: rabbitmq:3.6.1-management
        environment:
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_VHOST: vhost
        ports:
            - "15672:15672"
            - "5672:5672"